version: '3.9'

services:
  app:
    build:
      context: .
      # Need to install python3 due to ffi requirements in core. Once we release a new version of core removing the dep,
      # we can remove this.
      dockerfile_inline: |
        FROM node:20.2-alpine
        RUN apk add --no-cache libc6-compat python3 make g++ linux-headers
    restart: unless-stopped
    command: ["sh", "-c", "yarn install && exec yarn start"]
    init: true
    environment:
      - NODE_OPTIONS=--max-old-space-size=400 # Limit memory usage
      - POSTGRES_URL=postgres://app:password@localhost:6541/hub
    volumes:
      - .:/home/node/app
      - app_node_modules:/home/node/app/node_modules
    working_dir: /home/node/app
    networks:
      - my_network

volumes:
  app_node_modules:

networks:
  my_network:
